config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "top#show"

  scope(path_names: { new: "join" }) do
    resources :clients, only: %i(new create edit update)
  end

  scope(path_names: { new: "join" }) do
    resources :planners, only: %i(new create edit update)
  end

  namespace :planners do
    resources :available_frames, only: %i(index create destroy)
    resource :home, only: %i(show)
  end

  namespace :clients do
    resources :available_frames, only: %i(index)
    resources :reservations, only: %i(new create destroy)
    resource :home, only: %i(show)
  end

  scope :user do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_frame_cell.html.slim
/ reserve_button_enabled: 予約ボタンを表示するか
/ frames: available_frameのarray
/ 使うときはlist-groupクラスでラップする
.list-group-item.list-group-item-action.flex-column.align-items-start
  .container
    .row
      .col-auto.mr-auto
        .d-flex.w-100.justify-content-between
          h5.mb-1 = frame.planner.name
        p.mb-1 = frame.formatted_scheduled_time

      .col-auto
        - if reserve_button_enabled
          = button_to "予約する",
              clients_reservations_path(current_client),
              class: "btn btn-primary", method: :post,
              params: { reservation: { available_frame_id: frame.id } }

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  .container-fluid
    = link_to "FPConsul",
        logged_in? ? current_user.home_path : root_path,
        class: "navbar-brand"
    button.navbar-toggler.collapsed[
      type="button"
      data-toggle="collapse"
      data-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation"
    ]
      span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          - if logged_in?
            = link_to "Home", current_user.home_path, class: "nav-link"
      .form-inline.my-2.my-lg-0
        - if logged_in?
          = link_to "ログアウト", logout_path,
              method: :delete,
              class: "btn btn-warning my-2 my-sm-0"
        - else
          .nav-item.dropdown.mr-3.my-2.my-sm-0
            a.nav-link.dropdown-toggle.btn.btn-warning.btn-sm data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
              | 新規作成
            .dropdown-menu
              = link_to "クライアントとして作成", new_client_path, class: "dropdown-item"
              = link_to "プランナーとして作成", new_planner_path, class: "dropdown-item"
          .nav-item.mr-3
            = link_to "ログイン", login_path,
              class: "btn btn-warning my-2 my-sm-0"

app/views/shared/_reservation_cell.html.slim
/ reservation: 予約
/ 使うときはlist-groupクラスでラップする
.list-group-item.list-group-item-action.flex-column.align-items-start
  .container
    .row
      .col-auto.mr-auto
        .d-flex.w-100.justify-content-between
          - if current_user.planner?
            h5.mb-1 = reservation.client.name
          - elsif current_user.client?
            h5.mb-1 = reservation.available_frame.planner.name
        p.mb-1 = reservation.available_frame.formatted_scheduled_time

      .col-auto.d-flex.align-items-center
        - if current_user.client?
          = button_tag "取り消す",
              class: "btn btn-danger",
              type: "button",
              data: { toggle: "modal", target: "#confirmDestroyModal-#{reservation.id}"}

.modal.fade id="confirmDestroyModal-#{reservation.id}" tabindex=-1
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5.modal-title 確認
        button.close data-dismiss='modal' aria-label="キャンセル"
          span aria-hidden="true"
            | &times;
      .modal-body
        p#activate-frame-confirm-text = "以下の予約を取り消します."
        ul
          li = "プランナー: #{reservation.available_frame.planner.name}"
          li = "予約時間: #{reservation.available_frame.formatted_scheduled_time}"
      .modal-footer
        button.btn.btn-secondary type="button" data-dismiss="modal"
          | キャンセル
        = button_to "OK",
            clients_reservation_path(reservation),
            method: :delete,
            class: "btn btn-primary"