config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "top#show"

  scope(path_names: { new: "join" }) do
    resources :clients, only: %i(new create edit update)
  end

  scope(path_names: { new: "join" }) do
    resources :planners, only: %i(new create edit update)
  end

  namespace :planners do
    resources :available_frames, only: %i(index create destroy)
    resource :home, only: %i(show)
  end

  namespace :clients do
    resources :available_frames, only: %i(index)
    resources :reservations, only: %i(new create destroy)
    resource :home, only: %i(show)
  end

  scope :user do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/available_frame.rb
# frozen_string_literal: true

class AvailableFrame < ApplicationRecord
  scope :available, -> do
    left_joins(:reservation)
      .where(scheduled_time: Time.current...DateTime::Infinity.new)
      .where(reservations: { available_frame_id: nil })
  end

  before_destroy :prevent_destroy_if_reservation_exist

  belongs_to :planner
  has_one :reservation, dependent: :destroy

  validates :planner, presence: true
  validates :scheduled_time, presence: true
  validates :scheduled_time, scheduled_time: true, if: :scheduled_time
  validates :planner_id, uniqueness: { scope: [:scheduled_time] }

  private
    def prevent_destroy_if_reservation_exist
      if reservation
        errors.add(:this, "is already reserved by client")
        throw :abort
      end
    end
end

app/models/planner.rb
# frozen_string_literal: true

class Planner < User
  default_scope { where(user_type: :planner) }

  has_many :available_frames, dependent: :destroy
  has_many :reservations, dependent: :destroy, through: :available_frames
end

app/controllers/available_frames_controller.rb
# frozen_string_literal: true

class AvailableFramesController < ApplicationController
  before_action :logged_in_as_planner?

  def index
    @from = (params[:from]&.in_time_zone || Time.current).change(hour: 0, min: 0, sec: 0)
    to = @from.since(7.days)
    @available_frames = current_planner.available_frames.where(scheduled_time: (@from)..(to))
  end

  def create
    available_frame = current_planner.available_frames.build(available_frame_params)
    if available_frame.save
      flash[:success] = "予約枠を追加しました"
    else
      flash[:danger] = available_frame.errors.full_messages
    end
    redirect_to action: :index
  end

  def destroy
    begin
      available_frame = current_planner.available_frames.find(params[:id])
      available_frame.destroy!
      flash[:success] = "予約枠を削除しました"
    rescue ActiveRecord::RecordNotFound
      flash[:danger] = "存在しない予約枠です"
    rescue ActiveRecord::RecordNotDestroyed => err
      flash[:danger] = err.record.errors.full_messages
    end
    redirect_to action: :index
  end

  private
    def available_frame_params
      params.require(:available_frame).permit(
        :scheduled_time
      )
    end
end

app/controllers/clients/available_frames_controller.rb
# frozen_string_literal: true

class Clients::AvailableFramesController < ApplicationController
  include ClientConcern

  before_action :require_client_login!

  def index
    start_time = (params[:from]&.in_time_zone || Time.current) rescue Time.current

    @scheduled_time_from = start_time.beginning_of_day
    @scheduled_time_to = @scheduled_time_from.since(7.days)

    @available_frames = AvailableFrame.available.where(scheduled_time: (@scheduled_time_from)..(@scheduled_time_to))
  end
end

app/controllers/planners/available_frames_controller.rb
# frozen_string_literal: true

class Planners::AvailableFramesController < ApplicationController
  include PlannerConcern

  before_action :require_planner_login!

  def index
    start_time = (params[:from]&.in_time_zone || Time.current) rescue Time.current

    @scheduled_time_from = start_time.beginning_of_day
    @scheduled_time_to = @scheduled_time_from.since(7.days)

    @available_frames = current_planner.available_frames.where(scheduled_time: (@scheduled_time_from)..(@scheduled_time_to))
  end

  def create
    available_frame = current_planner.available_frames.build(available_frame_params)
    if available_frame.save
      flash[:success] = "予約枠を追加しました"
    else
      flash[:danger] = available_frame.errors.full_messages
    end
    redirect_to action: :index
  end

  def destroy
    available_frame = current_planner.available_frames.find(params[:id])
    available_frame.destroy!
    flash[:success] = "予約枠を削除しました"
  rescue ActiveRecord::RecordNotFound
    flash.now[:danger] = "存在しない予約枠です"
  rescue ActiveRecord::RecordNotDestroyed => err
    flash.now[:danger] = err.record.errors.full_messages
  ensure
    redirect_to action: :index
  end

  private
    def available_frame_params
      params.require(:available_frame).permit(
        :scheduled_time
      )
    end
end

app/controllers/planners/homes_controller.rb
# frozen_string_literal: true

class Planners::HomesController < ApplicationController
  include PlannerConcern

  before_action :require_planner_login!

  def show
    @reservations = current_planner.reservations
                      .joins([:available_frame, :client])
                      .eager_load([:available_frame, :client])
  end
end

app/controllers/planners_controller.rb
# frozen_string_literal: true

class PlannersController < ApplicationController
  include SessionConcern

  before_action :redirect_to_home, only: :new

  def new
    @planner = Planner.new
  end

  def show
  end

  def create
    @planner = Planner.new(planner_params)
    if @planner.save
      login(@planner)
      flash[:success] = "ユーザー登録が完了しました."
      redirect_to planners_home_path
    else
      flash.now[:danger] = @planner.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  private
    def planner_params
      params.require(:planner).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
      )
    end
end

app/helpers/available_frames_helper.rb
# frozen_string_literal: true

module AvailableFramesHelper
  delegate :date_range, to: FrameTable

  def time_ranges
    step_min = 30.minutes
    FrameTable.start_times.map do |start_time|
      end_time = start_time + step_min
      "#{start_time.strftime("%H:%M")} ~ #{end_time.strftime("%H:%M")}"
    end
  end

  def time_table(frames, start_day)
    frame_table = FrameTable.new(frames, start_day)
    time_ranges.zip(frame_table.to_matrix)
  end
end

app/views/planners/available_frames/index.html.slim
- content_for :head do
  = javascript_pack_tag "available_frames/index.js"

.container-fluid
  .row.mt-4.justify-content-between
    .col-sm-12.col-md-8.offset-md-2.col-lg-8.offset-lg-2
      .container-fluid
        .row.justify-content-between
          .col-4
            = link_to "前の週", planners_available_frames_path(from: @scheduled_time_from.ago(7.day)),
                class: "btn btn-primary"
          .col-4.text-right
            = link_to "次の週", planners_available_frames_path(from: @scheduled_time_to),
                class: "btn btn-primary"

  .row.mt-5.d-flex.align-item-center
    .col-sm-12.col-md-8.offset-md-2.col-lg-8.offset-lg-2
      table.table.table-bordered
        thead
          tr
            th scope="col"
              - date_range(@scheduled_time_from.to_date).each do |date|
                th scope="col"
                  div.text-center = date.strftime("%Y年 %m月 %d日 (%a)")
        tbody
          - time_table(@available_frames, @scheduled_time_from.to_date).each do |range, frames|
            tr
              th
                .text-center = range
                - frames.each do |frame|
                  / frame.idが存在する = 予約枠が既にセットされている．
                  / frame削除用のpathを精製する必要があり，それにframe.idを用いている(L31のdata-pathとして渡している)
                  / jsで削除確認用のモーダル内ボタンのhrefにしている

                  td class="#{frame.id ? "bg-success" : nil}"
                    .text-center.frame-cell = frame.id ? "○" : "×"
                    .text-center
                      - if frame.id
                        = button_tag "無効にする",
                            class: "available_frame-trigger-btn btn btn-light btn-sm",
                            type: "button",
                            data: { toggle: "modal", target: "#confirmInactivateModal", datetime: frame.datetime, path: planners_available_frame_path(frame.id)}
                      - else
                        = button_tag "有効にする",
                            class: "available_frame-trigger-btn btn btn-light btn-sm",
                            type: "button",
                            data: { toggle: "modal", target: "#confirmActivateModal", datetime: frame.datetime }

#confirmActivateModal.modal.fade tabindex=-1
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5.modal-title 確認
        button.close data-dismiss='modal' aria-label="キャンセル"
          span aria-hidden="true"
            | &times;
      .modal-body
        p#activate-frame-confirm-text
        = form_with(model: AvailableFrame.new, local: true, url: planners_available_frames_path) do |f|
          = f.text_field :scheduled_time, id: "available_frame-scheduled_time", class: "d-none"
          .modal-footer
            button.btn.btn-secondary type="button" data-dismiss="modal"
              | キャンセル
            = f.submit "OK", class: "btn btn-primary"

#confirmInactivateModal.modal.fade tabindex=-1
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5.modal-title 確認
        button.close data-dismiss="modal" aria-label='キャンセル'
          span aria-hidden="true"
            | &times;
      .modal-body
        p#inactivate-frame-confirm-text
          .modal-footer
            button.btn.btn-secondary type="button" data-dismiss="modal"
              | キャンセル
            = link_to '削除', "", id: "destroy-frame-link", class: 'btn btn-primary', method: :delete